Added error handling to output an unrecognized argument error

diff --git a/lib/setup b/lib/setup
--- a/lib/setup
+++ b/lib/setup
@@ -56,7 +56,9 @@ for i in "$@"
             --cron) CRON=1; shift;;
             --composer) COMPOSER=1; shift;;
 
-            *) ;;
+            *)
+                >&2 printf "\e[01;31mError: Unrecognized argument: %s\n" "${i}"
+                ;;
         esac
     done
 
