Moved error notice to the line below the banner.

diff --git a/lib/setup b/lib/setup
--- a/lib/setup
+++ b/lib/setup
@@ -60,7 +60,7 @@ for i in "$@"
             --composer) COMPOSER=1; shift;;
 
             *)
-                >&2 printf "\e[01;31mError: Unrecognized argument: %s\n" "${i}"
+                >&2 ERROR="$ERROR $i"
                 ;;
         esac
     done
@@ -74,6 +74,11 @@ if [[ ! -z "$@" ]] || [[ "$HELP" == "1" ]]; then
         '' \
         'https://mage2.click' \
         'https://github.com/mage2click/docker-magento-mutagen'
+
+    if [[ ! -z "$ERROR" ]]; then
+        echo
+        printf "\e[01;31mError: Unrecognized argument: %s\n\e[m" ${ERROR}
+    fi
 
     USAGE="
 Usage:
